[torch教程](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
import torch
import numpy
import time
import traceback

# Torch 的Tensor 和 numpy的ndarray

In [2]:
x = torch.empty(5,3) # 随机的
print(x)
print(type(x))
print(x.dtype)

tensor([[-6.3301e-29,  4.5859e-41, -6.3301e-29],
        [ 4.5859e-41, -3.2695e-31,  4.5859e-41],
        [-8.9430e-29,  4.5859e-41,  1.4013e-45],
        [ 4.5859e-41,  0.0000e+00,  0.0000e+00],
        [-4.2005e-34,  4.5859e-41,  0.0000e+00]])
<class 'torch.Tensor'>
torch.float32


In [3]:
x = torch.rand(5,3)
print(x)
print(x.dtype)

tensor([[0.2785, 0.4914, 0.2182],
        [0.4193, 0.6737, 0.9005],
        [0.1870, 0.2050, 0.8922],
        [0.5459, 0.1261, 0.9976],
        [0.5137, 0.2134, 0.1131]])
torch.float32


In [4]:
x = torch.zeros(5,3, dtype= torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [5]:
x = torch.tensor([5.5,3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


like 形状

In [7]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)    

tensor([[-0.2161, -0.8386, -1.5547],
        [-0.9105,  0.2367, -0.8144],
        [-0.2852,  0.0639,  2.9036],
        [ 0.6656, -0.0172, -0.3629],
        [-0.4799,  1.2853, -1.7308]])


In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


# 运算

In [9]:
y = torch.rand(5,3)
print(y)

tensor([[0.5089, 0.3141, 0.0311],
        [0.3043, 0.7370, 0.6449],
        [0.9519, 0.9082, 0.2803],
        [0.2429, 0.3405, 0.1069],
        [0.0584, 0.5520, 0.6156]])


In [10]:
y

tensor([[0.5089, 0.3141, 0.0311],
        [0.3043, 0.7370, 0.6449],
        [0.9519, 0.9082, 0.2803],
        [0.2429, 0.3405, 0.1069],
        [0.0584, 0.5520, 0.6156]])

In [11]:
print(x+y)

tensor([[ 0.2928, -0.5245, -1.5237],
        [-0.6062,  0.9736, -0.1695],
        [ 0.6667,  0.9721,  3.1840],
        [ 0.9085,  0.3232, -0.2560],
        [-0.4215,  1.8373, -1.1151]])


In [12]:
print(torch.add(x,y))

tensor([[ 0.2928, -0.5245, -1.5237],
        [-0.6062,  0.9736, -0.1695],
        [ 0.6667,  0.9721,  3.1840],
        [ 0.9085,  0.3232, -0.2560],
        [-0.4215,  1.8373, -1.1151]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.2928, -0.5245, -1.5237],
        [-0.6062,  0.9736, -0.1695],
        [ 0.6667,  0.9721,  3.1840],
        [ 0.9085,  0.3232, -0.2560],
        [-0.4215,  1.8373, -1.1151]])


In [14]:
# in-place 
print(y.add(x))

tensor([[ 0.2928, -0.5245, -1.5237],
        [-0.6062,  0.9736, -0.1695],
        [ 0.6667,  0.9721,  3.1840],
        [ 0.9085,  0.3232, -0.2560],
        [-0.4215,  1.8373, -1.1151]])


In [15]:
# 名字以_结尾的方法会把结果保存在张量中，修改原来的值

In [16]:
y.add_(x) # 结果保存在y中
print(y)

tensor([[ 0.2928, -0.5245, -1.5237],
        [-0.6062,  0.9736, -0.1695],
        [ 0.6667,  0.9721,  3.1840],
        [ 0.9085,  0.3232, -0.2560],
        [-0.4215,  1.8373, -1.1151]])


# 索引

In [17]:
print(x[:,1])
print(x[:,1].shape)

tensor([-0.8386,  0.2367,  0.0639, -0.0172,  1.2853])
torch.Size([5])


In [18]:
x = torch.randn(4,4)
print(x)

tensor([[-0.6405, -0.5057, -0.9197,  0.4275],
        [ 0.3439, -0.3983, -0.2468,  0.2744],
        [ 1.1139,  0.0358,  0.8202,  0.4452],
        [ 0.1648,  1.5729,  0.5856,  1.8340]])


### view函数, 改变形状, 是张量的一个引用. 在view这里改变数据,会影响原张量

In [19]:
y = x.view(16)

In [20]:
print(y)

tensor([-0.6405, -0.5057, -0.9197,  0.4275,  0.3439, -0.3983, -0.2468,  0.2744,
         1.1139,  0.0358,  0.8202,  0.4452,  0.1648,  1.5729,  0.5856,  1.8340])


In [21]:
y[0] = 1

In [22]:
print(x)

tensor([[ 1.0000, -0.5057, -0.9197,  0.4275],
        [ 0.3439, -0.3983, -0.2468,  0.2744],
        [ 1.1139,  0.0358,  0.8202,  0.4452],
        [ 0.1648,  1.5729,  0.5856,  1.8340]])


In [23]:
print(y)

tensor([ 1.0000, -0.5057, -0.9197,  0.4275,  0.3439, -0.3983, -0.2468,  0.2744,
         1.1139,  0.0358,  0.8202,  0.4452,  0.1648,  1.5729,  0.5856,  1.8340])


In [24]:
z = x.view(-1, 8) # -1 表示 从其他维度推断

In [25]:
z.shape

torch.Size([2, 8])

In [26]:
try:
    x.item() # item用于单元素张量
except Exception as  e:
    traceback.print_exc()
 

Traceback (most recent call last):
  File "<ipython-input-26-d3e1c76a8807>", line 2, in <module>
    x.item() # item用于单元素张量
ValueError: only one element tensors can be converted to Python scalars


In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0359])
1.035888433456421


# Numpy Bridge

和numpy互相转换

In [28]:
a = torch.ones(5)
print(a)
print(a.shape)
print(a.shape[0])

tensor([1., 1., 1., 1., 1.])
torch.Size([5])
5


In [29]:
b = a.numpy()
print(b)
print(b.dtype)
print(type(b))
print(b.shape)

[1. 1. 1. 1. 1.]
float32
<class 'numpy.ndarray'>
(5,)


In [30]:
c = a.clone() # clone
print(c)

tensor([1., 1., 1., 1., 1.])


In [31]:
d = torch.Tensor(a.size()).copy_(a)  # 等同于clone 
print(d)

tensor([1., 1., 1., 1., 1.])


In [32]:
a.add_(1)
print(a)
print(b)  # b也是对a的引用
print(c)
print(d)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


# GPU cuda

In [33]:
if torch.cuda.is_available():
    gpu_count = torch.cuda.device_count()
    print("gpu 数量:{}" .format(gpu_count))
    for i in range(gpu_count):
        print("gpu {} : {}".format(i, torch.cuda.get_device_name(i)))
    print('current gpu id:{}'.format(torch.cuda.current_device()))

gpu 数量:2
gpu 0 : GeForce GTX 1080
gpu 1 : GeForce GTX 1080
current gpu id:0


In [34]:
torch.device('cpu')

device(type='cpu')

In [35]:
torch.device('cuda')

device(type='cuda')

In [36]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [37]:
torch.device('cuda',1)

device(type='cuda', index=1)

In [38]:
torch.device('cuda',2)

device(type='cuda', index=2)

#### gpu和cpu之间切换

cpu 和 gpu之间的tensor属于不同的类型，不能直接相加

gpu init比较浪费时间

In [39]:

if torch.cuda.is_available():
    start_time = time.time()
    cpu = torch.device('cpu')
    gpu = torch.device('cuda')
    x = torch.randn(4,5,dtype=torch.float)
    y = torch.ones_like(x, device=gpu)
    a  = torch.randn(4,5,dtype=torch.float)
    print('x',x)
    print('y',y)
    end_time = time.time()
    print('init gpu', end_time - start_time)
    
    start_time = time.time()
    x = x.to(gpu)
    end_time = time.time()
    print('x from cpu to gpu', end_time - start_time)
    
    z = x + y   
    print(z)
    
    start_time = time.time()
    z.to("cpu",torch.double)
    end_time = time.time()
    print('z from gpu to cpu', end_time - start_time)
    print(z)
    
    # 尝试 cpu + gpu
    try:
        start_time = time.time()
        res = x + a
        end_time = time.time()
        print(x)
        print('add, gpu + cpu', end_time - start_time)
    except Exception as e:
        traceback.print_exc()


x tensor([[ 0.3900, -0.9608,  3.0336,  0.2126,  1.6592],
        [ 0.4656,  0.0935, -1.4014,  1.5755, -0.2005],
        [-1.1434, -0.2407, -1.3920,  1.0717, -0.1767],
        [ 0.3178, -0.9094,  1.5819, -1.2264, -1.5235]])
y tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')
init gpu 3.0354361534118652
x from cpu to gpu 0.00027632713317871094
tensor([[ 1.3900,  0.0392,  4.0336,  1.2126,  2.6592],
        [ 1.4656,  1.0935, -0.4014,  2.5755,  0.7995],
        [-0.1434,  0.7593, -0.3920,  2.0717,  0.8233],
        [ 1.3178,  0.0906,  2.5819, -0.2264, -0.5235]], device='cuda:0')
z from gpu to cpu 0.00014901161193847656
tensor([[ 1.3900,  0.0392,  4.0336,  1.2126,  2.6592],
        [ 1.4656,  1.0935, -0.4014,  2.5755,  0.7995],
        [-0.1434,  0.7593, -0.3920,  2.0717,  0.8233],
        [ 1.3178,  0.0906,  2.5819, -0.2264, -0.5235]], device='cuda:0')


Traceback (most recent call last):
  File "<ipython-input-39-ffaa5584cc42>", line 31, in <module>
    res = x + a
RuntimeError: expected backend CUDA and dtype Float but got backend CPU and dtype Float
